apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-cacerts-job
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: manufacturer-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabriclocal
        namespace: flux-fabriclocal
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: manufacturer
      component_name: manufacturer-net
      namespace: manufacturer-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://192.168.1.21:8200
      authpath: fabriclocalmanufacturer-net-auth
      secretcryptoprefix: kv/data/crypto/peerOrganizations/manufacturer-net/ca
      secretcredentialsprefix: kv/data/credentials/manufacturer-net/ca/manufacturer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=CH/ST=Zurich/L=Zurich/O=Manufacturer/CN=ca.manufacturer-net
