apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabriclocal
        namespace: flux-fabriclocal
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
 
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin 
  
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://192.168.1.21:8200
      authpath: fabriclocalcarrier-net-auth
      secretcert: kv/data/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: kv/data/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: kv/data/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: develop.local.com
